export enum FeedbackTags {
  Engaging = "Engaging",
  Challenging = "Challenging",
  Helpful = "Helpful",
  Unclear = "Unclear",
  Fun = "Fun",
  Interactive = "Interactive",
  Flexible = "Flexible",
  Innovative = "Innovative",
  Clear = "Clear",
  Practical = "Practical",
  Demanding = "Demanding",
  Straightforward = "Straightforward",
  Technical = "Technical",
  TheoryHeavy = "Theory-heavy",
  Advanced = "Advanced",
  Introductory = "Introductory",
  Confusing = "Confusing",
  Disorganized = "Disorganized",
  Boring = "Boring",
  Outdated = "Outdated",
  Inflexible = "Inflexible",
}
